version: "3.4"

services:
    webradio:
        image: ${DOCKER_REGISTRY-}webradio
        container_name: webradio
        build:
            context: .
            dockerfile: webradio/Dockerfile
        volumes:
            - deezer-cache:/tmp/deezer-cache

    deezer:
        image: ${DOCKER_REGISTRY-}deezerservice
        container_name: deezer
        build:
            context: .
            dockerfile: deezer-service/Dockerfile
        volumes:
            - deezer-cache:/tmp/deezer-cache

    redis:
        image: redis:alpine
        container_name: redis
        volumes:
            - redis-data:/data
        restart: unless-stopped

volumes:
    redis-data:
    deezer-cache:
