<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
		<RootNamespace>DeezerService</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Protobuf Include="Protos\webradio.proto" GrpcServices="Server" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.60.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.6" />
		<PackageReference Include="DeezNET" Version="1.2.2" />
	</ItemGroup>
</Project>
